'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: C4
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
  EfficientNet-B2:
    resources:
      instance-type: P4000
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
      vehciles_tdg_test2:
        type: dataset
        with:
          ref: dsrz5za640fptze
    uses: script@v1
    with:
      script: |-
        pip install scikit-learn
        ls
        ls /inputs/
        python /inputs/repo/train_vehicles.py \
          --batch_size 8 \
          --epochs 2 \
          --train_dir /inputs/vehciles_tdg_test2/2022-02-03_merged_tfrecords_500/train/ \
          --val_dir /inputs/vehciles_tdg_test2/2022-02-03_merged_tfrecords_500/val/ \
          --test_dir /inputs/vehciles_tdg_test2/2022-02-03_merged_tfrecords_500/test/ \
          --model_dir /inputs/repo/efficientnet_classifier   
      image: tensorflow/tensorflow:2.7.1